# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vstreamer_protos/commander/commander.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*vstreamer_protos/commander/commander.proto\x12\nvoicerecog\"[\n\x07\x43ommand\x12*\n\x06\x63hains\x18\x01 \x03(\x0b\x32\x1a.voicerecog.OperationChain\x12$\n\x07operand\x18\x02 \x01(\x0b\x32\x13.voicerecog.Operand\"]\n\x07Operand\x12 \n\x05sound\x18\x01 \x01(\x0b\x32\x11.voicerecog.Sound\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x11\n\tfile_path\x18\x03 \x01(\t\x12\x0f\n\x07\x66ilters\x18\x04 \x03(\t\"E\n\x05Sound\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0c\n\x04rate\x18\x02 \x01(\r\x12\x0e\n\x06\x66ormat\x18\x03 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x04 \x01(\x05\"@\n\x0eOperationChain\x12.\n\noperations\x18\x01 \x03(\x0b\x32\x1a.voicerecog.OperationRoute\"\xb4\x01\n\x0eOperationRoute\x12(\n\toperation\x18\x01 \x01(\x0e\x32\x15.voicerecog.Operation\x12\x0e\n\x06remote\x18\x02 \x01(\t\x12\x38\n\x07queries\x18\x03 \x03(\x0b\x32\'.voicerecog.OperationRoute.QueriesEntry\x1a.\n\x0cQueriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x1a\n\x08Response\x12\x0e\n\x06result\x18\x01 \x01(\x08*\xae\x01\n\tOperation\x12\x0e\n\nTRANSCRIBE\x10\x00\x12\r\n\tTRANSLATE\x10\x01\x12\x0c\n\x08SUBTITLE\x10\x02\x12\x17\n\x13SUBTITLE_TRANSLATED\x10\x03\x12\x07\n\x03TTS\x10\x04\x12\x06\n\x02VC\x10\x05\x12\x0c\n\x08PLAYBACK\x10\x06\x12\t\n\x05PAUSE\x10\x07\x12\n\n\x06RESUME\x10\x08\x12\n\n\x06RELOAD\x10\t\x12\x0f\n\x0bSET_FILTERS\x10\n\x12\x08\n\x04PING\x10\x0b\x32\x90\x01\n\tCommander\x12>\n\x0fprocess_command\x12\x13.voicerecog.Command\x1a\x14.voicerecog.Response\"\x00\x12\x43\n\x14sync_process_command\x12\x13.voicerecog.Command\x1a\x14.voicerecog.Response\"\x00\x42+Z)github.com/sondeko143/vstreamer-protos/gob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vstreamer_protos.commander.commander_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z)github.com/sondeko143/vstreamer-protos/go'
  _OPERATIONROUTE_QUERIESENTRY._options = None
  _OPERATIONROUTE_QUERIESENTRY._serialized_options = b'8\001'
  _OPERATION._serialized_start=595
  _OPERATION._serialized_end=769
  _COMMAND._serialized_start=58
  _COMMAND._serialized_end=149
  _OPERAND._serialized_start=151
  _OPERAND._serialized_end=244
  _SOUND._serialized_start=246
  _SOUND._serialized_end=315
  _OPERATIONCHAIN._serialized_start=317
  _OPERATIONCHAIN._serialized_end=381
  _OPERATIONROUTE._serialized_start=384
  _OPERATIONROUTE._serialized_end=564
  _OPERATIONROUTE_QUERIESENTRY._serialized_start=518
  _OPERATIONROUTE_QUERIESENTRY._serialized_end=564
  _RESPONSE._serialized_start=566
  _RESPONSE._serialized_end=592
  _COMMANDER._serialized_start=772
  _COMMANDER._serialized_end=916
# @@protoc_insertion_point(module_scope)
